# Generated by Django 4.2.30 on 2026-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('instructor', models.CharField(max_length=150)),
                ('schedule', models.CharField(help_text='e.g. Mon/Wed 10:00–11:30', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('seats_left', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
